export const users = [
  {
    id: 1,
    country: 'IT',
    name: 'Daniel',
    age: 44,
    profession: 'manager',
    married: true,
  },
  {
    id: 2,
    country: 'FR',
    name: 'Mia',
    age: 32,
    profession: 'musician',
    married: true,
  },
  {
    id: 3,
    country: 'US',
    name: 'Luca',
    age: 26,
    profession: 'programmer',
    married: true,
  },
  {
    id: 4,
    country: 'FR',
    name: 'Aria',
    age: 24,
    profession: 'musician',
    married: false,
  },
  {
    id: 5,
    country: 'IT',
    name: 'Aurora',
    age: 30,
    profession: 'manager',
    married: true,
  },
  {
    id: 6,
    country: 'FR',
    name: 'Michael',
    age: 41,
    profession: 'programmer',
    married: false,
  },
  {
    id: 7,
    country: 'US',
    name: 'William',
    age: 21,
    profession: 'musician',
    married: false,
  },
  {
    id: 8,
    country: 'US',
    name: 'Grace',
    age: 25,
    profession: 'programmer',
    married: true,
  },
  {
    id: 9,
    country: 'GR',
    name: 'Jack',
    age: 27,
    profession: 'programmer',
    married: false,
  },
  {
    id: 10,
    country: 'GR',
    name: 'Maya',
    age: 33,
    profession: 'manager',
    married: true,
  },
];
